import assert from "node:assert/strict";
import fs from "node:fs";

const incidentsJs = fs.readFileSync("data/incidents.js", "utf8");
const vmtJs = fs.readFileSync("data/vmt.js", "utf8");
const faultClaude = fs.readFileSync("data/faultfrac-claude.csv", "utf8");
const faultCodex = fs.readFileSync("data/faultfrac-codex.csv", "utf8");
const faultGemini = fs.readFileSync("data/faultfrac-gemini.csv", "utf8");
const snapshotsDoc = fs.readFileSync("data/snapshots/README.md", "utf8");

assert.ok(
  incidentsJs.startsWith("/* Generated by data/slurp.py from live NHTSA ADS current+archive CSVs"),
  `Replicata: inspect the top of data/incidents.js.
Expectata: the generated incident artifact declares that data/slurp.py built it from live NHTSA data and local fault inputs.
Resultata: the file header was ${JSON.stringify(incidentsJs.split("\\n", 1)[0])}.`,
);

assert.ok(
  vmtJs.startsWith("/* Generated by data/slurp.py from the live VMT Google Sheet export."),
  `Replicata: inspect the top of data/vmt.js.
Expectata: the generated VMT artifact declares that data/slurp.py built it from the live VMT sheet.
Resultata: the file header was ${JSON.stringify(vmtJs.split("\\n", 1)[0])}.`,
);

for (const [name, text] of [
  ["claude", faultClaude],
  ["codex", faultCodex],
  ["gemini", faultGemini],
]) {
  const lines = text.split("\n");
  assert.equal(
    lines[0],
    "reportID,speed,crashwith,svhit,cphit,severity,faultfrac,reasoning",
    `Replicata: inspect the header row of data/faultfrac-${name}.csv.
Expectata: each editable fault CSV stays plain canonical CSV with the standard header on line 1.
Resultata: the header row was ${JSON.stringify(lines[0])}.`,
  );
}

assert.ok(
  snapshotsDoc.includes("intentionally kept as raw fetched payloads") &&
    snapshotsDoc.includes("do not get inline provenance comments"),
  `Replicata: inspect data/snapshots/README.md.
Expectata: raw snapshot provenance is documented there instead of mutating the archived CSV payloads.
Resultata: the expected snapshot-provenance explanation was missing.`,
);

console.log("qual pass: data artifacts declare provenance without mutating raw upstream snapshots");
